# iphone_exif_key = ['filename', 'GPSInfo', 'ResolutionUnit', 'ExifOffset', 'Make', 'Model', 'Software', 'Orientation', 'DateTime', 
#                 'XResolution', 'YResolution', 'HostComputer', 'ExifVersion', 'ComponentsConfiguration', 'ShutterSpeedValue', 
#                 'DateTimeOriginal', 'DateTimeDigitized', 'ApertureValue', 'BrightnessValue', 'ExposureBiasValue', 
#                 'MeteringMode', 'Flash', 'FocalLength', 'ColorSpace', 'ExifImageWidth', 'DigitalZoomRatio', 
#                 'FocalLengthIn35mmFilm', 'SceneCaptureType', 'OffsetTime', 'OffsetTimeOriginal', 'OffsetTimeDigitized', 
#                 'SubsecTimeOriginal', 'SubjectLocation', 'SubsecTimeDigitized', 'ExifImageHeight', 'SensingMethod', 
#                 'ExposureTime', 'FNumber', 'SceneType', 'ExposureProgram', 'ISOSpeedRatings', 'ExposureMode', 
#                 'FlashPixVersion', 'WhiteBalance', 'LensSpecification', 'LensMake', 'LensModel', 'CompositeImage']

generic_exif_key = ['filename', 'GPSInfo', 'ResolutionUnit', 'ExifOffset', 'Make', 'Model', 'Software', 'Orientation', 'DateTime', 
                'XResolution', 'YResolution', 'HostComputer', 'ExifVersion', 'ComponentsConfiguration', 'ShutterSpeedValue', 
                'DateTimeOriginal', 'DateTimeDigitized', 'ApertureValue', 'BrightnessValue', 'ExposureBiasValue', 
                'MeteringMode', 'Flash', 'FocalLength', 'ColorSpace', 'ExifImageWidth', 'DigitalZoomRatio', 
                'FocalLengthIn35mmFilm', 'SceneCaptureType', 'OffsetTime', 'OffsetTimeOriginal', 'OffsetTimeDigitized', 
                'SubsecTimeOriginal', 'SubjectLocation', 'SubsecTimeDigitized', 'ExifImageHeight', 'SensingMethod', 
                'ExposureTime', 'FNumber', 'SceneType', 'ExposureProgram', 'ISOSpeedRatings', 'ExposureMode', 
                'FlashPixVersion', 'WhiteBalance', 'LensSpecification', 'LensMake', 'LensModel', 'CompositeImage']

# iphoneV3_exif = ['SourceFile', 'ExifToolVersion', 'FileName', 'Directory', 'FileSize', 'FileModifyDate', 'FileAccessDate',
#                  'FileCreateDate', 'FilePermissions', 'FileType', 'FileTypeExtension', 'MIMEType', 'ExifByteOrder', 'ImageWidth',
#                  'ImageHeight', 'EncodingProcess', 'BitsPerSample', 'ColorComponents', 'YCbCrSubSampling', 'PhotometricInterpretation',
#                  'Make', 'Model', 'Orientation', 'XResolution', 'YResolution', 'ResolutionUnit', 'Software', 'ModifyDate',
#                  'YCbCrPositioning', 'ExposureTime', 'FNumber', 'ExposureProgram', 'ISO', 'ExifVersion', 'DateTimeOriginal',
#                  'CreateDate', 'ComponentsConfiguration', 'ShutterSpeedValue', 'ApertureValue', 'BrightnessValue', 'ExposureCompensation',
#                  'MeteringMode', 'Flash', 'FocalLength', 'SubjectArea', 'SubSecTimeOriginal', 'SubSecTimeDigitized', 'FlashpixVersion',
#                  'ColorSpace', 'ExifImageWidth', 'ExifImageHeight', 'SensingMethod', 'SceneType', 'ExposureMode', 'WhiteBalance',
#                  'FocalLengthIn35mmFormat', 'SceneCaptureType', 'LensInfo', 'LensMake', 'LensModel', 'GPSLatitudeRef', 'GPSLatitude',
#                  'GPSLongitudeRef', 'GPSLongitude', 'GPSAltitudeRef', 'GPSAltitude', 'GPSSpeedRef', 'GPSSpeed', 'GPSImgDirectionRef',
#                  'GPSImgDirection', 'GPSDestBearingRef', 'GPSDestBearing', 'MakerNoteVersion', 'RunTimeFlags', 'RunTimeValue',
#                  'RunTimeScale', 'RunTimeEpoch', 'AEStable', 'AETarget', 'AEAverage', 'AFStable', 'AccelerationVector', 'FocusDistanceRange',
#                  'OISMode', 'ImageCaptureType', 'LivePhotoVideoIndex', 'PhotosAppFeatureFlags', 'HDRHeadroom', 'AFPerformance',
#                  'SignalToNoiseRatio', 'PhotoIdentifier', 'ColorTemperature', 'CameraType', 'FocusPosition', 'HDRGain', 'AFMeasuredDepth',
#                  'AFConfidence', 'SemanticStyle', 'XMPToolkit', 'CreateDate', 'CreatorTool', 'ModifyDate', 'Lens', 'LensInfo', 'DateCreated',
#                  'ProfileCMMType', 'ProfileVersion', 'ProfileClass', 'ColorSpaceData', 'ProfileConnectionSpace', 'ProfileDateTime',
#                  'ProfileFileSignature', 'PrimaryPlatform', 'CMMFlags', 'DeviceManufacturer', 'DeviceModel', 'DeviceAttributes', 'RenderingIntent',
#                  'ConnectionSpaceIlluminant', 'ProfileCreator', 'ProfileID', 'ProfileDescription', 'ProfileCopyright', 'MediaWhitePoint',
#                  'RedMatrixColumn', 'GreenMatrixColumn', 'BlueMatrixColumn', 'RedTRC', 'ChromaticAdaptation', 'BlueTRC', 'GreenTRC',
#                  'RunTimeSincePowerUp', 'Aperture', 'ImageSize', 'Megapixels', 'ScaleFactor35efl', 'ShutterSpeed', 'SubSecCreateDate',
#                  'SubSecDateTimeOriginal', 'GPSAltitude', 'GPSLatitude', 'GPSLongitude', 'CircleOfConfusion', 'FOV', 'FocalLength35efl',
#                  'GPSPosition', 'HyperfocalDistance', 'LightValue', 'LensID']

iphone_exif_key = ['SourceFile', 'ExifToolVersion', 'FileName', 'Directory', 'FileSize', 'FileModifyDate', 'FileAccessDate', 
                    'FileCreateDate', 'FilePermissions', 'FileType', 'FileTypeExtension', 'MIMEType', 'ExifByteOrder', 
                    'CurrentIPTCDigest', 'ImageWidth', 'ImageHeight', 'EncodingProcess', 'BitsPerSample', 'ColorComponents', 
                    'YCbCrSubSampling', 'Make', 'Model', 'XResolution', 'YResolution', 'ResolutionUnit', 'Software', 'ModifyDate', 
                    'Copyright', 'ExposureTime', 'FNumber', 'ExposureProgram', 'ISO', 'ExifVersion', 'DateTimeOriginal', 'CreateDate', 
                    'OffsetTime', 'OffsetTimeOriginal', 'OffsetTimeDigitized', 'ShutterSpeedValue', 'ApertureValue', 'BrightnessValue', 
                    'ExposureCompensation', 'MeteringMode', 'FocalLength', 'SubjectArea', 'SubSecTimeOriginal', 'ColorSpace', 
                    'SensingMethod', 'SceneType', 'ExposureMode', 'WhiteBalance', 'FocalLengthIn35mmFormat', 'Saturation', 'Sharpness', 
                    'LensInfo', 'LensMake', 'LensModel', 'Compression', 'ThumbnailOffset', 'ThumbnailLength', 'ThumbnailImage', 
                    'DisplayedUnitsX', 'DisplayedUnitsY', 'CopyrightFlag', 'PhotoshopThumbnail', 'IPTCDigest', 'CodedCharacterSet', 
                    'ApplicationRecordVersion', 'Keywords', 'DateCreated', 'TimeCreated', 'DigitalCreationDate', 'DigitalCreationTime', 
                    'CopyrightNotice', 'ProfileCMMType', 'ProfileVersion', 'ProfileClass', 'ColorSpaceData', 'ProfileConnectionSpace', 
                    'ProfileDateTime', 'ProfileFileSignature', 'PrimaryPlatform', 'CMMFlags', 'DeviceManufacturer', 'DeviceModel', 
                    'DeviceAttributes', 'RenderingIntent', 'ConnectionSpaceIlluminant', 'ProfileCreator', 'ProfileID', 'ProfileCopyright', 
                    'ProfileDescription', 'MediaWhitePoint', 'MediaBlackPoint', 'RedMatrixColumn', 'GreenMatrixColumn', 'BlueMatrixColumn', 
                    'DeviceMfgDesc', 'DeviceModelDesc', 'ViewingCondDesc', 'ViewingCondIlluminant', 'ViewingCondSurround', 
                    'ViewingCondIlluminantType', 'Luminance', 'MeasurementObserver', 'MeasurementBacking', 'MeasurementGeometry', 
                    'MeasurementFlare', 'MeasurementIlluminant', 'Technology', 'RedTRC', 'GreenTRC', 'BlueTRC', 'XMPToolkit', 
                    'DistortionCorrectionAlreadyApplied', 'LateralChromaticAberrationCorrectionAlreadyApplied', 'Lens', 'LensInfo', 
                    'Format', 'CreatorTool', 'MetadataDate', 'DocumentID', 'InstanceID', 'OriginalDocumentID', 'PreservedFileName', 
                    'Marked', 'RawFileName', 'Version', 'CompatibleVersion', 'ProcessVersion', 'IncrementalTemperature', 'IncrementalTint', 
                    'Exposure2012', 'Contrast2012', 'Highlights2012', 'Shadows2012', 'Whites2012', 'Blacks2012', 'Texture', 'Clarity2012', 
                    'Dehaze', 'Vibrance', 'ParametricShadows', 'ParametricDarks', 'ParametricLights', 'ParametricHighlights', 
                    'ParametricShadowSplit', 'ParametricMidtoneSplit', 'ParametricHighlightSplit', 'LuminanceSmoothing', 
                    'ColorNoiseReduction', 'HueAdjustmentRed', 'HueAdjustmentOrange', 'HueAdjustmentYellow', 'HueAdjustmentGreen', 
                    'HueAdjustmentAqua', 'HueAdjustmentBlue', 'HueAdjustmentPurple', 'HueAdjustmentMagenta', 'SaturationAdjustmentRed', 
                    'SaturationAdjustmentOrange', 'SaturationAdjustmentYellow', 'SaturationAdjustmentGreen', 'SaturationAdjustmentAqua', 
                    'SaturationAdjustmentBlue', 'SaturationAdjustmentPurple', 'SaturationAdjustmentMagenta', 'LuminanceAdjustmentRed', 
                    'LuminanceAdjustmentOrange', 'LuminanceAdjustmentYellow', 'LuminanceAdjustmentGreen', 'LuminanceAdjustmentAqua', 
                    'LuminanceAdjustmentBlue', 'LuminanceAdjustmentPurple', 'LuminanceAdjustmentMagenta', 'SplitToningShadowHue', 
                    'SplitToningShadowSaturation', 'SplitToningHighlightHue', 'SplitToningHighlightSaturation', 'SplitToningBalance', 
                    'ColorGradeMidtoneHue', 'ColorGradeMidtoneSat', 'ColorGradeShadowLum', 'ColorGradeMidtoneLum', 
                    'ColorGradeHighlightLum', 'ColorGradeBlending', 'ColorGradeGlobalHue', 'ColorGradeGlobalSat', 'ColorGradeGlobalLum', 
                    'AutoLateralCA', 'LensProfileEnable', 'LensManualDistortionAmount', 'VignetteAmount', 'DefringePurpleAmount', 
                    'DefringePurpleHueLo', 'DefringePurpleHueHi', 'DefringeGreenAmount', 'DefringeGreenHueLo', 'DefringeGreenHueHi', 
                    'PerspectiveUpright', 'PerspectiveVertical', 'PerspectiveHorizontal', 'PerspectiveRotate', 'PerspectiveAspect', 
                    'PerspectiveScale', 'PerspectiveX', 'PerspectiveY', 'GrainAmount', 'PostCropVignetteAmount', 'ShadowTint', 'RedHue', 
                    'RedSaturation', 'GreenHue', 'GreenSaturation', 'BlueHue', 'BlueSaturation', 'ConvertToGrayscale', 'OverrideLookVignette', 
                    'ToneCurveName2012', 'CameraProfile', 'CameraProfileDigest', 'LensProfileSetup', 'LensProfileName', 'LensProfileFilename', 
                    'LensProfileDistortionScale', 'LensProfileChromaticAberrationScale', 'LensProfileVignettingScale', 'HasSettings', 
                    'CropTop', 'CropLeft', 'CropBottom', 'CropRight', 'CropAngle', 'CropWidth', 'CropHeight', 'CropUnits', 
                    'CropConstrainToWarp', 'HasCrop', 'AlreadyApplied', 'ToneMapStrength', 'LookName', 'LookAmount', 'LookTable', 
                    'LookUUID', 'LookGroup', 'LookParameters', 'LookSupportsMonochrome', 'LookSupportsOutputReferred', 'VersionCreateDate', 
                    'VersionModifyDate', 'VersionCreateEditor', 'VersionModifyEditor', 'LightValue', 'SubSecCreateDate', 'SubSecDateTimeOriginal', 
                    'SubSecModifyDate', 'GPSDateTime']

