# iphone_exif_key = ['filename', 'GPSInfo', 'ResolutionUnit', 'ExifOffset', 'Make', 'Model', 'Software', 'Orientation', 'DateTime', 
#                 'XResolution', 'YResolution', 'HostComputer', 'ExifVersion', 'ComponentsConfiguration', 'ShutterSpeedValue', 
#                 'DateTimeOriginal', 'DateTimeDigitized', 'ApertureValue', 'BrightnessValue', 'ExposureBiasValue', 
#                 'MeteringMode', 'Flash', 'FocalLength', 'ColorSpace', 'ExifImageWidth', 'DigitalZoomRatio', 
#                 'FocalLengthIn35mmFilm', 'SceneCaptureType', 'OffsetTime', 'OffsetTimeOriginal', 'OffsetTimeDigitized', 
#                 'SubsecTimeOriginal', 'SubjectLocation', 'SubsecTimeDigitized', 'ExifImageHeight', 'SensingMethod', 
#                 'ExposureTime', 'FNumber', 'SceneType', 'ExposureProgram', 'ISOSpeedRatings', 'ExposureMode', 
#                 'FlashPixVersion', 'WhiteBalance', 'LensSpecification', 'LensMake', 'LensModel', 'CompositeImage']

generic_exif_key = ['filename', 'GPSInfo', 'ResolutionUnit', 'ExifOffset', 'Make', 'Model', 'Software', 'Orientation', 'DateTime', 
                'XResolution', 'YResolution', 'HostComputer', 'ExifVersion', 'ComponentsConfiguration', 'ShutterSpeedValue', 
                'DateTimeOriginal', 'DateTimeDigitized', 'ApertureValue', 'BrightnessValue', 'ExposureBiasValue', 
                'MeteringMode', 'Flash', 'FocalLength', 'ColorSpace', 'ExifImageWidth', 'DigitalZoomRatio', 
                'FocalLengthIn35mmFilm', 'SceneCaptureType', 'OffsetTime', 'OffsetTimeOriginal', 'OffsetTimeDigitized', 
                'SubsecTimeOriginal', 'SubjectLocation', 'SubsecTimeDigitized', 'ExifImageHeight', 'SensingMethod', 
                'ExposureTime', 'FNumber', 'SceneType', 'ExposureProgram', 'ISOSpeedRatings', 'ExposureMode', 
                'FlashPixVersion', 'WhiteBalance', 'LensSpecification', 'LensMake', 'LensModel', 'CompositeImage']

# iphoneV3_exif = ['SourceFile', 'ExifToolVersion', 'FileName', 'Directory', 'FileSize', 'FileModifyDate', 'FileAccessDate',
#                  'FileCreateDate', 'FilePermissions', 'FileType', 'FileTypeExtension', 'MIMEType', 'ExifByteOrder', 'ImageWidth',
#                  'ImageHeight', 'EncodingProcess', 'BitsPerSample', 'ColorComponents', 'YCbCrSubSampling', 'PhotometricInterpretation',
#                  'Make', 'Model', 'Orientation', 'XResolution', 'YResolution', 'ResolutionUnit', 'Software', 'ModifyDate',
#                  'YCbCrPositioning', 'ExposureTime', 'FNumber', 'ExposureProgram', 'ISO', 'ExifVersion', 'DateTimeOriginal',
#                  'CreateDate', 'ComponentsConfiguration', 'ShutterSpeedValue', 'ApertureValue', 'BrightnessValue', 'ExposureCompensation',
#                  'MeteringMode', 'Flash', 'FocalLength', 'SubjectArea', 'SubSecTimeOriginal', 'SubSecTimeDigitized', 'FlashpixVersion',
#                  'ColorSpace', 'ExifImageWidth', 'ExifImageHeight', 'SensingMethod', 'SceneType', 'ExposureMode', 'WhiteBalance',
#                  'FocalLengthIn35mmFormat', 'SceneCaptureType', 'LensInfo', 'LensMake', 'LensModel', 'GPSLatitudeRef', 'GPSLatitude',
#                  'GPSLongitudeRef', 'GPSLongitude', 'GPSAltitudeRef', 'GPSAltitude', 'GPSSpeedRef', 'GPSSpeed', 'GPSImgDirectionRef',
#                  'GPSImgDirection', 'GPSDestBearingRef', 'GPSDestBearing', 'MakerNoteVersion', 'RunTimeFlags', 'RunTimeValue',
#                  'RunTimeScale', 'RunTimeEpoch', 'AEStable', 'AETarget', 'AEAverage', 'AFStable', 'AccelerationVector', 'FocusDistanceRange',
#                  'OISMode', 'ImageCaptureType', 'LivePhotoVideoIndex', 'PhotosAppFeatureFlags', 'HDRHeadroom', 'AFPerformance',
#                  'SignalToNoiseRatio', 'PhotoIdentifier', 'ColorTemperature', 'CameraType', 'FocusPosition', 'HDRGain', 'AFMeasuredDepth',
#                  'AFConfidence', 'SemanticStyle', 'XMPToolkit', 'CreateDate', 'CreatorTool', 'ModifyDate', 'Lens', 'LensInfo', 'DateCreated',
#                  'ProfileCMMType', 'ProfileVersion', 'ProfileClass', 'ColorSpaceData', 'ProfileConnectionSpace', 'ProfileDateTime',
#                  'ProfileFileSignature', 'PrimaryPlatform', 'CMMFlags', 'DeviceManufacturer', 'DeviceModel', 'DeviceAttributes', 'RenderingIntent',
#                  'ConnectionSpaceIlluminant', 'ProfileCreator', 'ProfileID', 'ProfileDescription', 'ProfileCopyright', 'MediaWhitePoint',
#                  'RedMatrixColumn', 'GreenMatrixColumn', 'BlueMatrixColumn', 'RedTRC', 'ChromaticAdaptation', 'BlueTRC', 'GreenTRC',
#                  'RunTimeSincePowerUp', 'Aperture', 'ImageSize', 'Megapixels', 'ScaleFactor35efl', 'ShutterSpeed', 'SubSecCreateDate',
#                  'SubSecDateTimeOriginal', 'GPSAltitude', 'GPSLatitude', 'GPSLongitude', 'CircleOfConfusion', 'FOV', 'FocalLength35efl',
#                  'GPSPosition', 'HyperfocalDistance', 'LightValue', 'LensID']

# iphone_exif_key = ['SourceFile', 'ExifToolVersion', 'FileName', 'Directory', 'FileSize', 'FileModifyDate', 'FileAccessDate', 
#                     'FileCreateDate', 'FilePermissions', 'FileType', 'FileTypeExtension', 'MIMEType', 'ExifByteOrder', 
#                     'CurrentIPTCDigest', 'ImageWidth', 'ImageHeight', 'EncodingProcess', 'BitsPerSample', 'ColorComponents', 
#                     'YCbCrSubSampling', 'Make', 'Model', 'XResolution', 'YResolution', 'ResolutionUnit', 'Software', 'ModifyDate', 
#                     'Copyright', 'ExposureTime', 'FNumber', 'ExposureProgram', 'ISO', 'ExifVersion', 'DateTimeOriginal', 'CreateDate', 
#                     'OffsetTime', 'OffsetTimeOriginal', 'OffsetTimeDigitized', 'ShutterSpeedValue', 'ApertureValue', 'BrightnessValue', 
#                     'ExposureCompensation', 'MeteringMode', 'FocalLength', 'SubjectArea', 'SubSecTimeOriginal', 'ColorSpace', 
#                     'SensingMethod', 'SceneType', 'ExposureMode', 'WhiteBalance', 'FocalLengthIn35mmFormat', 'Saturation', 'Sharpness', 
#                     'LensInfo', 'LensMake', 'LensModel', 'Compression', 'ThumbnailOffset', 'ThumbnailLength', 'ThumbnailImage', 
#                     'DisplayedUnitsX', 'DisplayedUnitsY', 'CopyrightFlag', 'PhotoshopThumbnail', 'IPTCDigest', 'CodedCharacterSet', 
#                     'ApplicationRecordVersion', 'Keywords', 'DateCreated', 'TimeCreated', 'DigitalCreationDate', 'DigitalCreationTime', 
#                     'CopyrightNotice', 'ProfileCMMType', 'ProfileVersion', 'ProfileClass', 'ColorSpaceData', 'ProfileConnectionSpace', 
#                     'ProfileDateTime', 'ProfileFileSignature', 'PrimaryPlatform', 'CMMFlags', 'DeviceManufacturer', 'DeviceModel', 
#                     'DeviceAttributes', 'RenderingIntent', 'ConnectionSpaceIlluminant', 'ProfileCreator', 'ProfileID', 'ProfileCopyright', 
#                     'ProfileDescription', 'MediaWhitePoint', 'MediaBlackPoint', 'RedMatrixColumn', 'GreenMatrixColumn', 'BlueMatrixColumn', 
#                     'DeviceMfgDesc', 'DeviceModelDesc', 'ViewingCondDesc', 'ViewingCondIlluminant', 'ViewingCondSurround', 
#                     'ViewingCondIlluminantType', 'Luminance', 'MeasurementObserver', 'MeasurementBacking', 'MeasurementGeometry', 
#                     'MeasurementFlare', 'MeasurementIlluminant', 'Technology', 'RedTRC', 'GreenTRC', 'BlueTRC', 'XMPToolkit', 
#                     'DistortionCorrectionAlreadyApplied', 'LateralChromaticAberrationCorrectionAlreadyApplied', 'Lens', 'LensInfo', 
#                     'Format', 'CreatorTool', 'MetadataDate', 'DocumentID', 'InstanceID', 'OriginalDocumentID', 'PreservedFileName', 
#                     'Marked', 'RawFileName', 'Version', 'CompatibleVersion', 'ProcessVersion', 'IncrementalTemperature', 'IncrementalTint', 
#                     'Exposure2012', 'Contrast2012', 'Highlights2012', 'Shadows2012', 'Whites2012', 'Blacks2012', 'Texture', 'Clarity2012', 
#                     'Dehaze', 'Vibrance', 'ParametricShadows', 'ParametricDarks', 'ParametricLights', 'ParametricHighlights', 
#                     'ParametricShadowSplit', 'ParametricMidtoneSplit', 'ParametricHighlightSplit', 'LuminanceSmoothing', 
#                     'ColorNoiseReduction', 'HueAdjustmentRed', 'HueAdjustmentOrange', 'HueAdjustmentYellow', 'HueAdjustmentGreen', 
#                     'HueAdjustmentAqua', 'HueAdjustmentBlue', 'HueAdjustmentPurple', 'HueAdjustmentMagenta', 'SaturationAdjustmentRed', 
#                     'SaturationAdjustmentOrange', 'SaturationAdjustmentYellow', 'SaturationAdjustmentGreen', 'SaturationAdjustmentAqua', 
#                     'SaturationAdjustmentBlue', 'SaturationAdjustmentPurple', 'SaturationAdjustmentMagenta', 'LuminanceAdjustmentRed', 
#                     'LuminanceAdjustmentOrange', 'LuminanceAdjustmentYellow', 'LuminanceAdjustmentGreen', 'LuminanceAdjustmentAqua', 
#                     'LuminanceAdjustmentBlue', 'LuminanceAdjustmentPurple', 'LuminanceAdjustmentMagenta', 'SplitToningShadowHue', 
#                     'SplitToningShadowSaturation', 'SplitToningHighlightHue', 'SplitToningHighlightSaturation', 'SplitToningBalance', 
#                     'ColorGradeMidtoneHue', 'ColorGradeMidtoneSat', 'ColorGradeShadowLum', 'ColorGradeMidtoneLum', 
#                     'ColorGradeHighlightLum', 'ColorGradeBlending', 'ColorGradeGlobalHue', 'ColorGradeGlobalSat', 'ColorGradeGlobalLum', 
#                     'AutoLateralCA', 'LensProfileEnable', 'LensManualDistortionAmount', 'VignetteAmount', 'DefringePurpleAmount', 
#                     'DefringePurpleHueLo', 'DefringePurpleHueHi', 'DefringeGreenAmount', 'DefringeGreenHueLo', 'DefringeGreenHueHi', 
#                     'PerspectiveUpright', 'PerspectiveVertical', 'PerspectiveHorizontal', 'PerspectiveRotate', 'PerspectiveAspect', 
#                     'PerspectiveScale', 'PerspectiveX', 'PerspectiveY', 'GrainAmount', 'PostCropVignetteAmount', 'ShadowTint', 'RedHue', 
#                     'RedSaturation', 'GreenHue', 'GreenSaturation', 'BlueHue', 'BlueSaturation', 'ConvertToGrayscale', 'OverrideLookVignette', 
#                     'ToneCurveName2012', 'CameraProfile', 'CameraProfileDigest', 'LensProfileSetup', 'LensProfileName', 'LensProfileFilename', 
#                     'LensProfileDistortionScale', 'LensProfileChromaticAberrationScale', 'LensProfileVignettingScale', 'HasSettings', 
#                     'CropTop', 'CropLeft', 'CropBottom', 'CropRight', 'CropAngle', 'CropWidth', 'CropHeight', 'CropUnits', 
#                     'CropConstrainToWarp', 'HasCrop', 'AlreadyApplied', 'ToneMapStrength', 'LookName', 'LookAmount', 'LookTable', 
#                     'LookUUID', 'LookGroup', 'LookParameters', 'LookSupportsMonochrome', 'LookSupportsOutputReferred', 'VersionCreateDate', 
#                     'VersionModifyDate', 'VersionCreateEditor', 'VersionModifyEditor', 'LightValue', 'SubSecCreateDate', 'SubSecDateTimeOriginal', 
#                     'SubSecModifyDate', 'GPSDateTime']

iphone_exif_key = [
    'SourceFile',
    'ExifTool:ExifToolVersion',
    'File:FileName',
    'File:Directory',
    'File:FileSize',
    'File:FileModifyDate',
    'File:FileAccessDate',
    'File:FileCreateDate',
    'File:FilePermissions',
    'File:FileType',
    'File:FileTypeExtension',
    'File:MIMEType',
    'File:ExifByteOrder',
    'File:CurrentIPTCDigest',
    'File:ImageWidth',
    'File:ImageHeight',
    'File:EncodingProcess',
    'File:BitsPerSample',
    'File:ColorComponents',
    'File:YCbCrSubSampling',
    'EXIF:Make',
    'EXIF:Model',
    'EXIF:XResolution',
    'EXIF:YResolution',
    'EXIF:ResolutionUnit',
    'EXIF:Software',
    'EXIF:ModifyDate',
    'EXIF:Copyright',
    'EXIF:ExposureTime',
    'EXIF:FNumber',
    'EXIF:ExposureProgram',
    'EXIF:ISO',
    'EXIF:ExifVersion',
    'EXIF:DateTimeOriginal',
    'EXIF:CreateDate',
    'EXIF:OffsetTime',
    'EXIF:OffsetTimeOriginal',
    'EXIF:OffsetTimeDigitized',
    'EXIF:ShutterSpeedValue',
    'EXIF:ApertureValue',
    'EXIF:BrightnessValue',
    'EXIF:ExposureCompensation',
    'EXIF:MeteringMode',
    'EXIF:FocalLength',
    'EXIF:SubjectArea',
    'EXIF:SubSecTimeOriginal',
    'EXIF:ColorSpace',
    'EXIF:SensingMethod',
    'EXIF:SceneType',
    'EXIF:ExposureMode',
    'EXIF:WhiteBalance',
    'EXIF:FocalLengthIn35mmFormat',
    'EXIF:Saturation',
    'EXIF:Sharpness',
    'EXIF:LensInfo',
    'EXIF:LensMake',
    'EXIF:LensModel',
    'EXIF:Compression',
    'EXIF:ThumbnailOffset',
    'EXIF:ThumbnailLength',
    'EXIF:ThumbnailImage',
    'Photoshop:XResolution',
    'Photoshop:DisplayedUnitsX',
    'Photoshop:YResolution',
    'Photoshop:DisplayedUnitsY',
    'Photoshop:CopyrightFlag',
    'Photoshop:PhotoshopThumbnail',
    'Photoshop:IPTCDigest',
    'IPTC:CodedCharacterSet',
    'IPTC:ApplicationRecordVersion',
    'IPTC:Keywords',
    'IPTC:DateCreated',
    'IPTC:TimeCreated',
    'IPTC:DigitalCreationDate',
    'IPTC:DigitalCreationTime',
    'IPTC:CopyrightNotice',
    'ICC_Profile:ProfileCMMType',
    'ICC_Profile:ProfileVersion',
    'ICC_Profile:ProfileClass',
    'ICC_Profile:ColorSpaceData',
    'ICC_Profile:ProfileConnectionSpace',
    'ICC_Profile:ProfileDateTime',
    'ICC_Profile:ProfileFileSignature',
    'ICC_Profile:PrimaryPlatform',
    'ICC_Profile:CMMFlags',
    'ICC_Profile:DeviceManufacturer',
    'ICC_Profile:DeviceModel',
    'ICC_Profile:DeviceAttributes',
    'ICC_Profile:RenderingIntent',
    'ICC_Profile:ConnectionSpaceIlluminant',
    'ICC_Profile:ProfileCreator',
    'ICC_Profile:ProfileID',
    'ICC_Profile:ProfileCopyright',
    'ICC_Profile:ProfileDescription',
    'ICC_Profile:MediaWhitePoint',
    'ICC_Profile:MediaBlackPoint',
    'ICC_Profile:RedMatrixColumn',
    'ICC_Profile:GreenMatrixColumn',
    'ICC_Profile:BlueMatrixColumn',
    'ICC_Profile:DeviceMfgDesc',
    'ICC_Profile:DeviceModelDesc',
    'ICC_Profile:ViewingCondDesc',
    'ICC_Profile:ViewingCondIlluminant',
    'ICC_Profile:ViewingCondSurround',
    'ICC_Profile:ViewingCondIlluminantType',
    'ICC_Profile:Luminance',
    'ICC_Profile:MeasurementObserver',
    'ICC_Profile:MeasurementBacking',
    'ICC_Profile:MeasurementGeometry',
    'ICC_Profile:MeasurementFlare',
    'ICC_Profile:MeasurementIlluminant',
    'ICC_Profile:Technology',
    'ICC_Profile:RedTRC',
    'ICC_Profile:GreenTRC',
    'ICC_Profile:BlueTRC',
    'XMP:XMPToolkit',
    'XMP:DistortionCorrectionAlreadyApplied',
    'XMP:LateralChromaticAberrationCorrectionAlreadyApplied',
    'XMP:Lens',
    'XMP:LensInfo',
    'XMP:Format',
    'XMP:CreatorTool',
    'XMP:MetadataDate',
    'XMP:CreateDate',
    'XMP:ModifyDate',
    'XMP:DocumentID',
    'XMP:InstanceID',
    'XMP:OriginalDocumentID',
    'XMP:PreservedFileName',
    'XMP:Marked',
    'XMP:DateCreated',
    'XMP:RawFileName',
    'XMP:Version',
    'XMP:CompatibleVersion',
    'XMP:ProcessVersion',
    'XMP:WhiteBalance',
    'XMP:IncrementalTemperature',
    'XMP:IncrementalTint',
    'XMP:Exposure2012',
    'XMP:Contrast2012',
    'XMP:Highlights2012',
    'XMP:Shadows2012',
    'XMP:Whites2012',
    'XMP:Blacks2012',
    'XMP:Texture',
    'XMP:Clarity2012',
    'XMP:Dehaze',
    'XMP:Vibrance',
    'XMP:Saturation',
    'XMP:ParametricShadows',
    'XMP:ParametricDarks',
    'XMP:ParametricLights',
    'XMP:ParametricHighlights',
    'XMP:ParametricShadowSplit',
    'XMP:ParametricMidtoneSplit',
    'XMP:ParametricHighlightSplit',
    'XMP:Sharpness',
    'XMP:LuminanceSmoothing',
    'XMP:ColorNoiseReduction',
    'XMP:HueAdjustmentRed',
    'XMP:HueAdjustmentOrange',
    'XMP:HueAdjustmentYellow',
    'XMP:HueAdjustmentGreen',
    'XMP:HueAdjustmentAqua',
    'XMP:HueAdjustmentBlue',
    'XMP:HueAdjustmentPurple',
    'XMP:HueAdjustmentMagenta',
    'XMP:SaturationAdjustmentRed',
    'XMP:SaturationAdjustmentOrange',
    'XMP:SaturationAdjustmentYellow',
    'XMP:SaturationAdjustmentGreen',
    'XMP:SaturationAdjustmentAqua',
    'XMP:SaturationAdjustmentBlue',
    'XMP:SaturationAdjustmentPurple',
    'XMP:SaturationAdjustmentMagenta',
    'XMP:LuminanceAdjustmentRed',
    'XMP:LuminanceAdjustmentOrange',
    'XMP:LuminanceAdjustmentYellow',
    'XMP:LuminanceAdjustmentGreen',
    'XMP:LuminanceAdjustmentAqua',
    'XMP:LuminanceAdjustmentBlue',
    'XMP:LuminanceAdjustmentPurple',
    'XMP:LuminanceAdjustmentMagenta',
    'XMP:SplitToningShadowHue',
    'XMP:SplitToningShadowSaturation',
    'XMP:SplitToningHighlightHue',
    'XMP:SplitToningHighlightSaturation',
    'XMP:SplitToningBalance',
    'XMP:ColorGradeMidtoneHue',
    'XMP:ColorGradeMidtoneSat',
    'XMP:ColorGradeShadowLum',
    'XMP:ColorGradeMidtoneLum',
    'XMP:ColorGradeHighlightLum',
    'XMP:ColorGradeBlending',
    'XMP:ColorGradeGlobalHue',
    'XMP:ColorGradeGlobalSat',
    'XMP:ColorGradeGlobalLum',
    'XMP:AutoLateralCA',
    'XMP:LensProfileEnable',
    'XMP:LensManualDistortionAmount',
    'XMP:VignetteAmount',
    'XMP:DefringePurpleAmount',
    'XMP:DefringePurpleHueLo',
    'XMP:DefringePurpleHueHi',
    'XMP:DefringeGreenAmount',
    'XMP:DefringeGreenHueLo',
    'XMP:DefringeGreenHueHi',
    'XMP:PerspectiveUpright',
    'XMP:PerspectiveVertical',
    'XMP:PerspectiveHorizontal',
    'XMP:PerspectiveRotate',
    'XMP:PerspectiveAspect',
    'XMP:PerspectiveScale',
    'XMP:PerspectiveX',
    'XMP:PerspectiveY',
    'XMP:GrainAmount',
    'XMP:PostCropVignetteAmount',
    'XMP:ShadowTint',
    'XMP:RedHue',
    'XMP:RedSaturation',
    'XMP:GreenHue',
    'XMP:GreenSaturation',
    'XMP:BlueHue',
    'XMP:BlueSaturation',
    'XMP:ConvertToGrayscale',
    'XMP:OverrideLookVignette',
    'XMP:ToneCurveName2012',
    'XMP:CameraProfile',
    'XMP:CameraProfileDigest',
    'XMP:LensProfileSetup',
    'XMP:LensProfileName',
    'XMP:LensProfileFilename',
    'XMP:LensProfileDistortionScale',
    'XMP:LensProfileChromaticAberrationScale',
    'XMP:LensProfileVignettingScale',
    'XMP:HasSettings',
    'XMP:CropTop',
    'XMP:CropLeft',
    'XMP:CropBottom',
    'XMP:CropRight',
    'XMP:CropAngle',
    'XMP:CropWidth',
    'XMP:CropHeight',
    'XMP:CropUnits',
    'XMP:CropConstrainToWarp',
    'XMP:HasCrop',
    'XMP:AlreadyApplied',
    'XMP:ToneMapStrength',
    'XMP:LookName',
    'XMP:LookAmount',
    'XMP:LookTable',
    'XMP:LookUUID',
    'XMP:LookGroup',
    'XMP:LookParameters',
    'XMP:LookSupportsMonochrome',
    'XMP:LookSupportsOutputReferred',
    'XMP:VersionCreateDate',
    'XMP:VersionModifyDate',
    'XMP:VersionCreateEditor',
    'XMP:VersionModifyEditor',
    'Composite:LightValue',
    'Composite:SubSecCreateDate',
    'Composite:SubSecDateTimeOriginal',
    'Composite:SubSecModifyDate',
    'Composite:GPSDateTime'
]

